---
default: true
MD013: false # Ignore long lines
MD033: false # Ignore inline HTML
MD041: false # Ignore images without alt tags
MD031: false # Ignore blocks of code with no blank line before or after (chirpy code block file name annotation)
