
---
version: '3'

tasks:
  default:
    silent: true
    cmd: task -l

  jekyll:dev:
    desc: Start a development server that also builds future posts.
    dir: website
    cmd: bundle exec jekyll serve --incremental --future --drafts --livereload --force_polling
