---
version: '3'


tasks:
  default:
    silent: true
    cmd: task -l

  dev:
    desc: Start a development server that also builds future posts.
    cmd: bundle exec jekyll serve --future

  img:convert:
    desc: Convert all png images to webp and remove the originals.
    vars:
      PNG_FILES:
        sh: find assets/img/posts -type f -name *.png | tr '\n' ' '
    cmds:
      - for: { var: PNG_FILES }
        cmd: |
          file={{.ITEM}}
          cwebp -q 100 "$file" -o "${file%.png}.webp"
          rm $file