---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build and Publish Docker Image

on:
  workflow_dispatch:
    inputs:
      custom-tag:
        type: string
        description: Additional custom tags for the image.
        required: false
  pull_request:
    paths:
      - "website/**"
      - "Dockerfile"
      - ".github/workflows/docker-release.yaml"
  push:
    tags: ["*"]

jobs:
  build:
    uses: mirceanton/reusable-workflows/.github/workflows/docker-release.yaml@main
    secrets: inherit
    with:
      image-name: ghcr.io/${{ github.repository }}
      platforms: linux/amd64, linux/arm64
      custom-tag: ${{ inputs.custom-tag }}
