---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build and Publish Docker Image

on:
  pull_request:
    paths: [ "website/*", "Dockerfile", ".github/workflows/docker.yaml" ]
  push:
    tags: [ "*" ]


env:
  REGISTRY_IMAGE: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}

jobs:
  build:
    uses: mirceanton/reusable-workflows/.github/workflows/docker-release.yaml@main
    secrets: inherit
