---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build and Publish Docker Image

on:
  push:
    branches: [ main ]
    paths:
      - website/*
      - Dockerfile

  workflow_dispatch:
    inputs:
      custom-tag:
        description: "Custom tag for the image"
        type: string
        required: false

env:
  REGISTRY_IMAGE: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}

jobs:
  generate-tag:
    runs-on: "ubuntu-latest"
    outputs:
      tags: ${{ steps.generator.outputs.tags }}

    steps:
      - name: Install prerqeuisites
        run: sudo apt update && sudo apt install -y curl jq

      - name: Checkout the Repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Generate Calver Tag
        id: generator
        env:
          REGISTRY_USER: "${{ github.repository_owner }}"
          REGISTRY_TOKEN: "${{ secrets.GHCR_RW_TOKEN }}"
          REGISTRY_URL: ghcr.io
          IMAGE_NAME: ${{ github.event.repository.name }}
        run: echo "tags=$(bash scripts/generate_calver_tag.sh)" | tee "$GITHUB_OUTPUT"

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@5927c834f5b4fdf503fca6f4c7eccda82949e1ee # v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4fd812986e6c8c2a69e18311145f9371337f27d4 # v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_RW_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            latest
            type=sha
            ${{ needs.generate-tag.outputs.tags }}
            ${{ github.event.inputs.custom-tag }}

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@1a162644f9a7e87d8f4b053101d1d9a712edc18c # v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
