---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release

on:
  # Manual Trigger
  workflow_dispatch: {}

  # Run on any website content change
  push:
    branches: ["main"]
    paths:
      - "website/**"

jobs:
  release:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-release-calver.yaml@e7fc0b68ce5b8bf0f4c85d53928f91af6ec54357 # v3.4.36
    secrets: inherit
