---
name: Release
permissions: { contents: read }

on:
  pull_request:
    branches: ['main']
    paths: ["website/**", "website/.github/workflows/git-release.yaml"]

  push:
    branches: ['main']
    paths: ["website/**"]

  workflow_dispatch:
    inputs:
      dry-run:
        description: Dry Run
        default: false
        required: false
        type: boolean
      draft:
        description: Draft Release
        default: false
        required: false
        type: boolean

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Create Release
        uses: mirceanton/action-calver-release@5cd262a2c16b0310855514f6a63bab7769d09e1c # 2025.5.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: |
            ${{ 
              ( github.event.inputs.dry-run == 'true' && github.event_name == 'workflow_dispatch' ) ||
              github.event_name == 'pull_request'
            }}
