---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release

on:
  workflow_dispatch: {}
  push:
    branches: [ "main" ]
    paths: [ "website/**", "Dockerfile" ]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Create Release
        shell: bash
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          # Retrieve previous release tag
          previous_tag="$(gh release list --limit 1 | awk '{ print $1 }')"

          # Extract major, minor and patch from tag
          previous_major="${previous_tag%%\.*}"
          previous_minor="${previous_tag#*.}"
          previous_minor="${previous_minor%.*}"
          previous_patch="${previous_tag##*.}"

          # Determine next release tag
          next_major_minor="$(date +'%Y').$(date +'%-m')"
          if [[ "${previous_major}.${previous_minor}" == "${next_major_minor}" ]]; then
              echo "Month release already exists for year, incrementing patch number by 1"
              next_patch="$((previous_patch + 1))"
          else
              echo "Month release does not exist for year, setting patch number to 0"
              next_patch="0"
          fi
          release_tag="${next_major_minor}.${next_patch}"

          # Create release
          gh release create "${release_tag}" \
              --repo="${GITHUB_REPOSITORY}" \
              --title="${release_tag}" \
              --generate-notes
