---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release

on:
  # Manual Trigger
  workflow_dispatch: {}

  # Run on any website content change
  push:
    branches: ["main"]
    paths:
      - "website/**"

jobs:
  release:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-release-calver.yaml@0d9c406821566c38302d9af7c59ccfc4d6416c68 # v3.4.46
    secrets: inherit
