---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release

on:
  # Manual Trigger
  workflow_dispatch: {}

  # Run on any website content change
  push:
    branches: ["main"]
    paths:
      - "website/**"

jobs:
  release:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-release-calver.yaml@9ce913356128f964413b5fe99efe4858e18d7831 # v3.4.51
    secrets: inherit
