---
name: Jekyll Build site

on:
  pull_request: {}

jobs:
  jekyll-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install jekyll and bundler
        run: |
          sudo gem install bundler jekyll
          bundler --version
          jekyll --version
      - name: Install gems
        run: sudo bundle install --gemfile=website/Gemfile

      - name: Run jekyll build
        run: |
          cd website/
          bundle exec jekyll build --trace
