---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Link Checker

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 0 * * *" # Every day at midnight
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/link-checker.yaml"
      - "website/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - ".github/workflows/link-checker.yaml"
      - "website/**"

env:
  WORKFLOW_ISSUE_TITLE: "Link Checker Dashboard 🔗"

jobs:
  build-site:
    uses: ./.github/workflows/jekyll-build.yaml
    with:
      upload-artifact: true
      artifact-name: "${{ github.sha }}"

  link-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Download Site Files
        uses: actions/download-artifact@v4
        with:
          path: ./site

      - name: Check Links
        id: link-checker
        uses: lycheeverse/lychee-action@v1
        with:
          args: --config=.github/lychee.toml './site/**/*.html'
          format: markdown
          output: lychee.md
          fail: false

      - name: Generate Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Find Link Checker Issue
        id: find-issue
        run: |
          issue_number=$( \
              gh issue list \
                  --search "in:title ${{ env.WORKFLOW_ISSUE_TITLE }}" \
                  --state open \
                  --json number \
                  | jq --raw-output '.[0].number' \
          )
          echo "issue-number=${issue_number}" >> $GITHUB_OUTPUT
          echo "${issue_number}"
        env:
          GH_TOKEN: "${{ steps.app-token.outputs.token }}"

      - name: Create or Update Issue
        uses: peter-evans/create-issue-from-file@v5
        with:
          token: "${{ steps.app-token.outputs.token }}"
          title: "${{ env.WORKFLOW_ISSUE_TITLE }}"
          issue-number: "${{ steps.find-issue.outputs.issue-number || '' }}"
          content-filepath: ${{ steps.link-checker.outputs.output-file }}
