---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Link Checker

on:
  workflow_dispatch: {}
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/link-checker.yaml"
      - "website/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - ".github/workflows/link-checker.yaml"
      - "website/**"

env:
  WORKFLOW_ISSUE_TITLE: "Link Checker Dashboard 🔗"

jobs:
  lychee:
    name: Lychee
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4

      - name: Build Site
        uses: mirceanton/mirceanton.com/.github/actions/jekyll-build@feat/link-checker-workflow
        id: jekyll-builder
        with:
          jekyll-dir: website/

      - name: Check Links
        id: link-checker
        uses: lycheeverse/lychee-action@v1
        with:
          args: --config=.github/lychee.toml 'website/_site/**/*.html'
          format: markdown
          output: lychee.md
          fail: false

      - name: Generate Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Find Link Checker Issue
        uses: mirceanton/mirceanton.com/.github/actions/issue-finder@feat/link-checker-workflow
        id: find-issue
        with:
          title: "${{ env.WORKFLOW_ISSUE_TITLE }}"
          token: "${{ steps.app-token.outputs.token }}"

      - name: Create or Update Issue
        uses: peter-evans/create-issue-from-file@v5
        with:
          token: "${{ steps.app-token.outputs.token }}"
          title: "${{ env.WORKFLOW_ISSUE_TITLE }}"
          issue-number: "${{ steps.find-issue.outputs.issue-number || '' }}"
          content-filepath: ${{ steps.link-checker.outputs.output-file }}
