---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Markdownlint
permissions: { contents: read }

on:
  workflow_dispatch: {}
  push:
    paths:
      - ".github/workflows/markdownlint.yaml"
      - ".mise.toml"
      - "**.md"

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup mise
        uses: jdx/mise-action@bfb9fa0b029db830a8c570757cee683df207a6c5 # v2.4.0

      - name: Run markdownlint
        run: mise exec -- markdownlint '**/*.md'
