---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Label Sync

on:
  workflow_dispatch: {}  # Manual Trigger
  push:
    branches: [ "main" ]
    paths: [ ".github/labels.yaml" ]
  schedule:
    - cron: "0 0 * * *" # Every day at midnight

permissions:
  issues: write

jobs:
  label-sync:
    uses: mirceanton/reusable-workflows/.github/workflows/meta-label-sync.yaml@main
    with:
      config-file: .github/configs/labels.yaml
    secrets: inherit
