---
name: Run Renovate


on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: Dry Run
        default: "false"
        required: false
  schedule:
    - cron: "0 * * * *"  # hourly
  push:
    branches: [ main ]
  pull_request: {}


concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true


jobs:
  renovate:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Renovate
        run: npm install renovate@37.367.0 github-app-installation-token@1.2.0

      - name: Generate GitHub App Token
        id: app-token
        run: |
          npm run github-app-installation-token \
            --appId ${{ secrets.BOT_APP_ID }} \
            --installationId  ${{ secrets.BOT_APP_INSTALLATION_ID }} \
            --privateKey ${{ secrets.BOT_APP_PRIVATE_KEY }}

      - name: Run Renovate
        run: npm run renovate
        env:
          LOG_LEVEL: debug
          RENOVATE_PLATFORM: github
          RENOVATE_PLATFORM_COMMIT: true
          RENOVATE_DRY_RUN: "${{ inputs.dryRun == true }}"
          RENOVATE_AUTODISCOVER: true
          RENOVATE_AUTODISCOVER_FILTER: "${{ github.repository }}"
          RENOVATE_GIT_AUTHOR: 'Renovate Bot <bot@renovateapp.com>'
          # RENOVATE_CONFIG_FILE: ./github/renovate-config.json
          RENOVATE_TOKEN: "${{ steps.app-token.outputs.token }}"
