---
name: Run Renovate

on:
  workflow_dispatch: {}  # manual trigger
  schedule:
    - cron: "0 * * * *"  # hourly
  push:
    branches: [ main ]

jobs:
  renovate:
    runs-on: "ubuntu-latest"
    # container: ghcr.io/renovatebot/renovate:37.367.0-full

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4.1.5

      - name: Install bundler
        run: |
          sudo gem install bundler
          bundler --version
      
      - name: Install renovate
        run: |
          npm install renovate
          npx renovate
