---
name: Run Renovate


on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: Dry Run
        default: "false"
        required: false
  schedule:
    - cron: "0 * * * *"  # hourly
  push:
    branches: [ main ]
  pull_request: {}


concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true


env:
  LOG_LEVEL: debug
  RENOVATE_PLATFORM: github
  RENOVATE_PLATFORM_COMMIT: true
  RENOVATE_DRY_RUN: "${{ inputs.dryRun == true }}"
  RENOVATE_AUTODISCOVER: true
  RENOVATE_AUTODISCOVER_FILTER: "${{ github.repository }}"
  RENOVATE_GIT_AUTHOR: 'Renovate Bot <bot@renovateapp.com>'
  # RENOVATE_CONFIG_FILE: ./github/renovate-config.json


jobs:
  renovate:
    runs-on: "ubuntu-latest"
    steps:

      - name: Run Renovate
        env:
          GITHUB_COM_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: npx renovate
