---
name: Renovate

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: Dry Run
        default: "false"
        required: false
      logLevel:
        description: Log Level
        default: debug
        required: false
  schedule:
    - cron: "0 * * * *"  # hourly
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  renovate:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup Renovate
        run: npm install renovate@37.367.0

      - name: Generate Token
        uses: actions/create-github-app-token@31c86eb3b33c9b601a1f60f98dcbfd1d70f379b4 # v1
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Run Renovate
        run: npx renovate
        env:
          LOG_LEVEL: "${{ inputs.logLevel || 'debug' }}"
          RENOVATE_PLATFORM: github
          RENOVATE_PLATFORM_COMMIT: true
          RENOVATE_DRY_RUN: "${{ inputs.dryRun == true }}"
          RENOVATE_AUTODISCOVER: true
          RENOVATE_AUTODISCOVER_FILTER: "${{ github.repository }}"
          RENOVATE_GIT_AUTHOR: 'mr-borboto[bot] <170036086+mr-borboto[bot]@users.noreply.github.com>'
          RENOVATE_TOKEN: "${{ steps.app-token.outputs.token }}"
